import {
  IconAlertCircle,
  IconArrowLeft,
  IconArrowRight,
  IconBell,
  IconBolt,
  IconBrandGoogle,
  IconBrandGithub,
  IconBriefcase2,
  IconCalendar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconCopy,
  IconCreditCard,
  IconDownload,
  IconFileText,
  IconFlame,
  IconHelp,
  IconLayoutDashboard,
  IconLoader2,
  IconMail,
  IconMessageCircle,
  IconMoon,
  IconPlus,
  IconSearch,
  IconSettings,
  IconSun,
  IconTrash,
  IconUpload,
  IconUser,
  IconUsers,
  IconX,
  IconDotsVertical,
  IconEye,
  IconMessage,
  IconInfoCircle,
  IconPrinter,
  IconPhoto,
  IconDeviceFloppy,
  IconBriefcase,
  IconUserPin,
  IconLogin2,
  IconLayoutKanban,
  IconTypography,
  IconPencil,
  IconSend,
  IconLink,
  IconSelector,
  IconCircleDot,
  IconSquare,
  IconSquareCheck,
  IconMinus,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarRightCollapse,
  IconProps
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  add: IconPlus,
  minus: IconMinus,
  arrowLeft: IconArrowLeft,
  arrowRight: IconArrowRight,
  bell: IconBell,
  billing: IconCreditCard,
  bolt: IconBolt,
  calendar: IconCalendar,
  check: IconCheck,
  checkSquare: IconSquareCheck,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronDown: IconChevronDown,
  close: IconX,
  copy: IconCopy,
  dashboard: IconLayoutDashboard,
  download: IconDownload,
  ellipsis: IconDotsVertical,
  eye: IconEye,
  flame: IconFlame,
  google: IconBrandGoogle,
  github: IconBrandGithub,
  help: IconHelp,
  info: IconInfoCircle,
  mail: IconMail,
  media: IconPhoto,
  message: IconMessage,
  messageCircle: IconMessageCircle,
  moon: IconMoon,
  page: IconFileText,
  printer: IconPrinter,
  save: IconDeviceFloppy,
  search: IconSearch,
  settings: IconSettings,
  spinner: IconLoader2,
  square: IconSquare,
  sun: IconSun,
  trash: IconTrash,
  upload: IconUpload,
  user: IconUser,
  users: IconUsers,
  warning: IconAlertCircle,
  workspace: IconBriefcase2,
  briefcase: IconBriefcase,
  userPen: IconUserPin,
  login: IconLogin2,
  kanban: IconLayoutKanban,
  type: IconTypography,
  pen: IconPencil,
  send: IconSend,
  link: IconLink,
  select: IconSelector,
  circle: IconCircleDot,
  sidebarLeft: IconLayoutSidebarLeftCollapse,
  sidebarRight: IconLayoutSidebarRightCollapse
};
